### ISSUE TITLE
Remove NNP code and move to n2p2

### ISSUE THREAD

**Issue by streeve** [ECP-copa/CabanaMD#37]
Steps towards removing the n2p2 specific code:

- [x] Merge flexible AoSoA #30, templating over System and System_NNP (better interface to main n2p2 kernels)
- [x] Merge neighbor list update #43, templating over Neighbor
- [x] Merge update for NNP kernels 46 to use Cabana slices, rather than CabanaMD System
- [x] Merge template over device type #51 and clean up use of Kokkos Views for NNP
- [x] Merge into n2p2
- [x] Remove all NNP files except force_nnp* (wrapping n2p2 functions)
